services:
  mongodb:
    image: mongo:7.0.3
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.runCommand('ping').ok" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mongodb_data:/var/lib/mongodb/data
    env_file: .env.example
    ports:
      - "27017:27017"
    networks:
      - app-network

  analytics:
    build: .
    ports:
      - "8002:8002"
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - app-network
    env_file: .env.example
    entrypoint: "/entrypoint.sh"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge